export const clienteModel = {
  referenceId: 0,
  nombre: "",
  apellido_paterno:"",
  apellido_materno:"",
  calle: "",
  colonia: "",
  RFC:"",
  codigo_postal :0,
  correo:"",
  telefono:"",
  ciudad:"",
  estado: "",
  razon_social :"",
};
