export const sucursalModel = {
  referenceId: 0,
  nombre: "",
  calle: "",
  colonia: "",
  numero_exterior: "",
  numero_interior: "",
  codigo_postal: 0,
  municipio: "",
  estado: "",
  rfc_emisor: "",
  nombre_fiscal_emisor: "",
  regimen_fiscal_emisor: "",
  certificado_facturacion:"",
  key_facturacion:"",
  clave_facturacion:"",
  password_sifei :"",
  token_sifei_pdf:"",
  id_equipo_sifei:"",
  password_soap_sifei:"",
  user_sifei:"",
};
